# Author: romanp@google.com (Roman Perepelitsa)

package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "type_map",
    hdrs = ["type_map.h"],
    deps = [
    ],
)

cc_test(
    name = "type_map_test",
    size = "small",
    srcs = ["type_map_test.cc"],
    deps = [
        ":type_map",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "indenting_stream",
    hdrs = ["indenting_stream.h"],
    deps = [
    ],
)

cc_test(
    name = "indenting_stream_test",
    size = "small",
    srcs = ["indenting_stream_test.cc"],
    deps = [
        ":indenting_stream",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "stringstream",
    hdrs = ["stringstream.h"],
    deps = [
    ],
)
